### ISSUE TITLE
AttributeError: 'Script' object has no attribute 'exports_sync'

### ISSUE THREAD

**Issue by df13954** [zhanghecn/luckzh_fnative_monitor#1]
```
luck android native watch
Traceback (most recent call last):
  File "/Users/os/android/hook/github/luckzh_fnative_monitor/main/./luck_androidn_watch.py", line 45, in <module>
    main()
  File "/Users/os/android/hook/github/luckzh_fnative_monitor/main/./luck_androidn_watch.py", line 36, in main
    script.exports_sync.monitor(args.type,args.range)
AttributeError: 'Script' object has no attribute 'exports_sync'
```
环境是Python3.8
frida          14.2.2

---

大佬你好，这个工具是运行在那些frida版本中？

**Comment by Kare-c** [comment]
大佬 我也用同样的问题，有好的解决办法吗

**Comment by df13954** [comment]
> 大佬 我也用同样的问题，有好的解决办法吗

使用高版本frida，我换了16.0.9可以了

**Comment by zhanghecn** [comment]
看图像识 debug_cat 大佬   。
低版本frida 可以把 **luck_androidn_watch.py** 中的  ``script.exports_sync.monitor(args.type,args.range)`` 换成  ``script.exports.monitor(args.type,args.range)``
